routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



// Route::get('/', function () {
//     return view('login');
// });

Route::get('clear', function() {
   Artisan::call('config:cache');
   return 'Clear Cache Config Succesfull!';
});


Route::get('/', 'Auth\\LoginController@index')->name('admin.login');
Route::get('admin/tentang/panduan/view', 'TentangController@viewPanduan');
Route::get('admin/tentang/syarat/view', 'TentangController@viewSyarat');
Route::get('admin/tentang/kebijakan/view', 'TentangController@viewKebijakan');
Route::get('admin/tentang/bantuan/view', 'TentangController@viewBantuan');
Auth::routes();






Route::group(['middleware' => 'auth',  'prefix' => 'admin', 'as' => 'admin.'], function () {


    Route::resource('category', 'CategoryController');
    Route::get('/home', 'HomeController@index')->name('admin.home');

    Route::get('user/pengguna', 'UserController@pengguna');
  
  
    Route::get('user/admin', 'UserController@admin');
    Route::get('user/admin/create', 'UserController@adminCreate');
    Route::POST('user/admin/store', 'UserController@adminStore');
    Route::get('user/admin/edit/{id}', 'UserController@adminEdit');
       Route::get('user/admin/edit_list/{id}', 'UserController@adminEditList');
    
    Route::post('user/admin/update/{id}', 'UserController@adminUpdate');
    
       Route::post('user/admin/update/list/{id}', 'UserController@adminUpdateList');
    
    
    Route::post('user/pengguna/status/{id}', 'UserController@statusUSer');
    Route::post('user/pengguna/resetpass/{id}', 'UserController@resetPassUser');
    Route::post('user/pengguna/resetpin/{id}', 'UserController@resetPinUser');

    Route::resource('user', 'UserController');
    Route::resource('tag', 'TagController');
    Route::resource('post', 'PostController');

    Route::resource('roles', 'Admin\RolesController');
    Route::resource('permissions', 'Admin\PermissionsController');

    //baru
    Route::get('slider/api', 'SliderController@sliderAPI');
    Route::resource('slider', 'SliderController');
      Route::resource('slider_berita', 'SliderBeritaController');

    Route::post('topuphistory/masuk/verifikasi/{id}', 'TopUpHistoryController@verifikasiTopupMasuk');
    Route::post('topuphistory/masuk/reject/{id}', 'TopUpHistoryController@rejectTopupMasuk');

    Route::get('topuphistory/masuk', 'TopUpHistoryController@topupMasuk')->name('admin.topuphistory.masuk');
    Route::get('topuphistory/manual', 'TopUpHistoryController@topupManual');
    Route::get('topuphistory/admin_history', 'TopUpHistoryController@adminHistory');

    Route::get('topuphistory/point', 'TopUpHistoryController@tambahPointIndex');
    Route::post('topuphistory/point/add', 'TopUpHistoryController@tambahPoint');
    Route::post('topuphistory/admintopup', 'TopUpHistoryController@tambahkepeng');
    Route::resource('topuphistory', 'TopUpHistoryController');

    Route::get('kirim/history', 'KirimHistoryController@index');

    //pengaturan
    Route::get('pengaturan/fee', 'PengaturanController@fee');
    Route::post('pengaturan/fee/update', 'PengaturanController@updateFee');

    //tentang
    Route::get('tentang/panduan', 'TentangController@panduan');
    Route::get('tentang/syarat', 'TentangController@syarat');
    Route::get('tentang/kebijakan', 'TentangController@kebijakan');
    Route::get('tentang/bantuan', 'TentangController@bantuan');

    Route::get('tentang/', 'TentangController@index');
    Route::post('tentang/panduan/simpan', 'TentangController@storePanduan');
    Route::post('tentang/syarat/simpan', 'TentangController@storeSyarat');
    Route::post('tentang/kebijakan/simpan', 'TentangController@storeKebijakan');
    Route::post('tentang/bantuan/simpan', 'TentangController@storeBantuan');

    //pencairan
    Route::get('pencairan/history', 'PencairanController@history')->name('pencairan.history');
    Route::post('pencairan/verifikasi/{id}', 'PencairanController@verifikasi')->name('pencairan.verifikasi');
    Route::post('pencairan/reject/{id}', 'PencairanController@reject')->name('pencairan.reject');
    Route::resource('pencairan', 'PencairanController');
});


Route::get('autologin', function(){
    Auth::loginUsingId(1);

    return redirect()->to('/');
})->middleware('web');

app/Models/Topup.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
// use App\Models\Transaction;

class Topup extends Model
{
    protected $table="top_up_history";

    protected $fillable = [
        "verifikator",
        "status"
    ];

    public function invoice(){
        return $this->hasOne(Invoices::class, 'id_transaction', 'kode_unik');
    }
}

app/Http/Controllers/TopUpController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Auth;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Mail;
use App\Services\KepengService;

class TopUpController extends Controller
{
    public function __construct()
    {
        $this->kepengSvc = new KepengService();
    }

    public function store(Request $request)
    {
        try{
            $return = $this->kepengSvc
                ->setRequest($request)->setUser()
                ->topUp();
            
            return jsonResponseStatus(true, "Ok", $return);
        } catch (\Exception $e) {
            return jsonResponseStatus(false, "Error : ".$e->getMessage());
        }
    }

    public static function quickRandom($length = 3)
    {
        $pool = '0123456789';
        return substr(str_shuffle(str_repeat($pool, 5)), 0, $length);
    }
}

resources/views/admin/topup/action.blade.php
{{-- <a href="{{ route('admin.slider.edit',$id) }}" style="margin-bottom: 10px" class="btn btn-success btn-sm edit"
role="button" aria-pressed="true"><i class="fas fa-check-square"></i> Accept</a> --}}

{{-- <a href="#" id={{ $id }} style="margin-bottom: 10px" class="btn btn-success btn-sm verifikasi" role="button"
aria-pressed="true" data-toggle="modal" data-target="#modalDelete"> <i class="fas fa-check-square"></i>
Accept</a> --}}

<a href="#" id={{ $id }} style="margin-bottom: 10px" class="btn btn-success btn-sm delete" role="button"
    aria-pressed="true" data-toggle="modal" data-target="#modalDelete"> <i class="fas fa-check-square"></i>
    Accept</a>


<a href="#" id={{ $id }} style="margin-bottom: 10px" class="btn btn-secondary btn-sm reject" role="button"
    aria-pressed="true" data-toggle="modal" data-target="#modalDelete"> <i class="fas fa-minus-square"></i>
    Reject</a>

resources/views/admin/topup/delete.blade.php
<x-modal id="deleteModal" idForm="deleteForm">
    <x-slot name="footer">
        <x-button color="secondary" title="Batal" data-dismiss="modal" />
        <x-button color="danger" title="Hapus data" id="btnDelete" type="submit" />
    </x-slot>
</x-modal>

resources/views/admin/topup/index.blade.php
@extends('admin.partials.default')
@section('content')
<section class="section">

    <x-header>Top Up History User</x-header>
    {{-- <x-button id="btnCreate" style="margin-bottom: 10px" title="Add User" href="{{ route('post.create') }}"> --}}
    {{-- </x-button> --}}

    @table([ 'th' => ['no', 'kode_unik', 'Name','No Hp','Jumlah Topup','Trans Fee','Total','verifikator','Verifikasi','Tgl
    Verifikasi','Tgl Topup'],
    'id' => 'tbl-topup'])

</section>
<form id="deleteForm" method="POST" role="form">
    @csrf
    @method('delete')
    <x-modal id="deleteModal" idForm="deleteForm" title="Apakah anda yakin ingin menghapus post ?">

        <x-slot name="footer">
            <x-button color="secondary" title="Batal" data-dismiss="modal" />
            <button type="submit" class="btn btn-danger" onclick="formSubmit()">Delete Data
            </button>
        </x-slot>
    </x-modal>
</form>

<script type="text/javascript">
    $(function () {
          $.ajaxSetup({
              headers: {
                  'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
              }
        });
  
        table = $('#tbl-topup').DataTable({
                  processing:true,
                  serverSide:true,
                  pageLength: 5,
                  paging: true,
                  ajax: '{!! route('admin.topuphistory.index') !!}',
                  columns: [
                        { data: 'DT_RowIndex',orderable:false, searchable:false, width:'10px'}, 
                        { data: 'kode_unik'},
                        { data: 'nama'},
                        { data: 'no_hp'},
                       { data: 'kepeng', 
                          render: function(data, type, full, meta) {
                              var format = $.fn.dataTable.render.number( ',', '.', 0 ).display(data);
                              return 'Rp. '+format;
                              }},
                              { data: 'transaction_fee',  render: function(data, type, full, meta) {
                              var format = $.fn.dataTable.render.number( ',', '.', 0 ).display(data);
                              
                              return 'Rp. '+format;
                              }},
                              { data: 'total',  render: function(data, type, full, meta) {
                              var format = $.fn.dataTable.render.number( ',', '.', 0 ).display(data);
                              return 'Rp. '+format;
                              }},
                        { data: 'verifikator'},
                        { data: 'status'},
                        { data: 'updated_at' },
                        { data: 'created_at' },
                   
                     ]
              }); 
      });

      $('#tbl-users tbody').on('click', '.delete', function () {
              $('#deleteModal').modal('show');  
              id = $(this).attr('id'); 
              var url = id;
              $(" #deleteForm").attr('action', url); let data=table.row( $(this).parents('tr') ).data();
              $('#deleteModal .modal-title').text("Yakin ingin menghapus Post, " +data.name+" ?"); }); 
             function formSubmit() { 
                    $("#deleteForm").submit(); 
                } 
</script>

@endsection

resources/views/admin/topup/index_topup_masuk.blade.php
@extends('admin.partials.default')
@section('content')
<section class="section">

    <x-header>Top Up Masuk</x-header>
    {{-- <x-button id="btnCreate" style="margin-bottom: 10px" title="Add User" href="{{ route('post.create') }}"> --}}
    {{-- </x-button> --}}

    @table([ 'th' => ['no', 'kode Topup', 'User','No Hp','Jumlah Topup','Trans Fee','Total','Verifikasi','Tanggal
    Topup','Action'],
    'id' => 'tbl-topup'])

</section>


<form id="deleteForm" method="POST" role="form">
    @csrf
    @method('post')
    <x-modal id="deleteModal" idForm="deleteForm" title="">



        <x-slot name="footer">
            <div class="form-group">

                <input hidden type="text" class="form-control" id="no_hp2" name="no_hp" value="">
                <input hidden type="text" class="form-control" id="kepeng2" name="kepeng" value="">
                <input hidden type="text" class="form-control" id="kode2" name="kode" value="">
            </div>


            <button type="submit" class="btn btn-danger" title="Batal" data-dismiss="modal">Batal</button>
            <button type=" submit" class="btn btn-info" onclick="formSubmit()">Verifikasi</button>
        </x-slot>
    </x-modal>
</form>


<form id="rejectForm" method="POST" role="form">
    @csrf
    @method('post')
    <x-modal id="rejectModal" idForm="rejectForm" title="">



        <x-slot name="footer">

            <div class="form-group">
                <input hidden type="text" class="form-control" id="no_hp" name="no_hp" value="">
                <input hidden type="text" class="form-control" id="kepeng" name="kepeng" value="">
                <input hidden type="text" class="form-control" id="kode" name="kode" value="">
            </div>


            <button type="submit" class="btn btn-danger" title="Batal" data-dismiss="modal">Batal</button>
            <button type=" submit" class="btn btn-info" onclick="formSubmit()">Reject</button>
        </x-slot>
    </x-modal>
</form>


<script type="text/javascript">
    $(function () {
          $.ajaxSetup({
              headers: {
                  'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
              }
        });
  
        table = $('#tbl-topup').DataTable({
                  processing:true,
                  serverSide:true,
                  pageLength: 5,
                  paging: true,
                //   url:'admin/topuphistory/masuk',
                  ajax: '{!! url('admin/topuphistory/masuk') !!}',
                  columns: [
                        { data: 'DT_RowIndex',orderable:false, searchable:false, width:'10px'}, 
                        { data: 'kode_unik'},
                        { data: 'nama'},
                        { data: 'no_hp'},
                        { data: 'kepeng', 
                        render: function(data, type, full, meta) {
                              var format = $.fn.dataTable.render.number( ',', '.', 0 ).display(data);
                              return 'Rp. '+format;
                              }},
                              { data: 'transaction_fee',  render: function(data, type, full, meta) {
                              var format = $.fn.dataTable.render.number( ',', '.', 0 ).display(data);
                              
                              return 'Rp. '+format;
                              }},
                              { data: 'total',  render: function(data, type, full, meta) {
                              var format = $.fn.dataTable.render.number( ',', '.', 0 ).display(data);
                              return 'Rp. '+format;
                              }},
                        { data: 'status'},
                        { data: 'created_at' },
                        { data: 'action',width:'60px' }
                     ]
              }); 
      });


    $('#tbl-topup tbody').on('click', '.delete', function () {
              $('#deleteModal').modal('show');  
             let data=table.row($(this).parents('tr') ).data();
              var url = 'masuk/verifikasi/' + data.kode_unik;
              $("#deleteForm").attr('action', url); 
              document.getElementById("no_hp").value = data.no_hp; 
              document.getElementById("kepeng").value = data.kepeng; 
              document.getElementById("kode").value = data.kode_unik; 
              $('#deleteModal .modal-title').text("Apakah anda ingin memverifikasi top up dengan kode " +data.kode_unik+" ?"); }); 
             function formSubmit() { 
                    $("#deleteForm").submit(); 
            } 

            $('#tbl-topup tbody').on('click', '.reject', function () {
              $('#rejectModal').modal('show');  
             let data=table.row($(this).parents('tr') ).data();
              var url = 'masuk/reject/' + data.kode_unik;
              $("#rejectForm").attr('action', url); 
              document.getElementById("no_hp2").value = data.no_hp; 
              document.getElementById("kepeng2").value = data.kepeng; 
              document.getElementById("kode2").value = data.kode_unik; 
              $('#rejectModal .modal-title').text("Apakah anda ingin membatalkan top up dengan kode " +data.kode_unik+" ?"); }); 
             function formSubmit() { 
                    $("#rejectForm").submit(); 
            } 
</script>


@endsection

resources/views/admin/topup/top_up_manual.blade.php
@extends('admin.partials.default')
@section('content')

<section class="section">

    <x-header>Top up manual</x-header>
    {{-- <h2>belum ada data</h2> --}}
    @include('sweetalert::alert')

    <div class="card">
        <div class="card-body">




            <form id="poinform" action="{{ url('admin/topuphistory/admintopup') }}" enctype="multipart/form-data"
                method="POST">
                @csrf
                @method('post')
                @if ($errors->any())
                <div style="padding:20px; margin-bottom: 20px" class="aler alert-danger">
                    @foreach ($errors->all() as $err )
                    <li><span>{{ $err }}</span></li>
                    @endforeach
                </div>
                @endif


                <label>Pilih User</label>
                <div class="form-group">
                    <select id="no_hp" name="no_hp" class="form-control select2" style="width:100%!important;">
                        {{-- <option value="" holder></option> --}}
                        @foreach ($users as $item)
                        <option value="{{ $item->no_hp}},{{ $item->id}},{{ $item->name}},{{ $item->saldo}}">
                            {{ $item->name }} ( {{ $item->no_hp }}) </option>
                        @endforeach
                    </select>
                </div>

                <label>Saldo User Saat ini</label>
                <div class="form-group">
                    <input type="text" readonly="readonly" class="form-control" id="user_saldo" name="user_saldo"
                        rows="10">
                </div>


                <label>Pilih aksi</label>
                <div class="form-group">
                    <select id="aksi" name="aksi" class="form-control select2" style="width:100%!important;">
                        {{-- <option value="" holder></option> --}}

                        <option value="penambahan">Tambah</option>
                        <option value="pengurangan">Kurangi</option>

                    </select>
                </div>



                <div class="form-group">
                    <input type="text" class="form-control" id="user" name="user" rows="10">
                </div>


                <label>Masukan Jumlah kepeng</label>
                <div class="form-group">
                    <input type="text" class="form-control" id="kepeng2" name="kepeng2" rows="10">
                </div>
                <div class="form-group">
                    <input hidden type="text" class="form-control" id="kepeng" name="kepeng" rows="10">
                </div>

                {{-- <x-input id="kepeng" name="kepeng" label="Masukan Jumlah Kepeng" placeholder="0" /> --}}

                <button type="button" data-toggle="modal" data-target="#myModal" id="btn_confirm"
                    class="btn btn-primary">Proses
                    Sekarang</button>

            </form>
        </div>


    </div>

</section>
<x-modal id="deleteModal" idForm="deleteForm" title="">
    <x-slot name="footer">
        <x-button color="secondary" title="Batal" data-dismiss="modal" />
        <button type="submit" class="btn btn-info" onclick="formSubmit()">Verifikasi</button>
    </x-slot>
</x-modal>

<script>
    $('#deleteModal').on('show.bs.modal', function () {

$('.modal-title').text('My New Modal Title');

});

    $('#btn_confirm').on('click',  function () {
              $('#deleteModal').modal('show');  
           
              $("#deleteForm").attr('action', url); 
              $("#deleteModal #myModalLabel").text( title );
              $('#deleteModal title').text("Apakah anda ingin memverifikasi top up dengan kode " +data.kode_unik+" ?"); 
               }); 

               
             function formSubmit() { 
                    $("#poinform").submit(); 
            }
            



    document.getElementById("user").style.display = "none";
    data();
    $(function(){
  
    $('.select2').on('change', function() {
        
   data();
    
    });
  });

function data(){
    var data = $(".select2 option:selected").text();
      document.getElementById("user").value = $("#no_hp").val(); 
   
      var str = $("#no_hp").val();
      var n = str.lastIndexOf(',');
      var result = str.substring(n + 1);
      document.getElementById("user_saldo").value = 'Rp. '+rubah(result); 




// '$1,000.00'

     // 
}
  
function rubah(angka){
   var reverse = angka.toString().split('').reverse().join(''),
   ribuan = reverse.match(/\d{1,3}/g);
   ribuan = ribuan.join('.').split('').reverse().join('');
  
   return ribuan;

 }

 var rupiah = document.getElementById("kepeng2");
 var rupiah2 = document.getElementById("kepeng");



rupiah.addEventListener("keyup", function(e) {
  // tambahkan 'Rp.' pada saat form di ketik
  // gunakan fungsi formatRupiah() untuk mengubah angka yang di ketik menjadi format angka

var number = numeral(rupiah.value);
numeral.defaultFormat('0,0');
rupiah.value='Rp '+(number.format());
rupiah2.value=number.value();

//   rupiah.value = formatRupiah(this.value, "Rp. ");


 
});

/* Fungsi formatRupiah */
function formatRupiah(angka, prefix) {
  var number_string = angka.replace(/[^,\d]/g, "").toString(),
    split = number_string.split(","),
    sisa = split[0].length % 3,
    rupiah = split[0].substr(0, sisa),
    ribuan = split[0].substr(sisa).match(/\d{3}/gi);

  // tambahkan titik jika yang di input sudah menjadi angka ribuan
  if (ribuan) {
    separator = sisa ? "." : "";
    rupiah += separator + ribuan.join(".");
  }

  rupiah = split[1] != undefined ? rupiah + "," + split[1] : rupiah;
  return prefix == undefined ? rupiah : rupiah ? "Rp. " + rupiah : "";
}



</script>

@endsection

resources/views/admin/topup/top_up_point.blade.php
@extends('admin.partials.default')
@section('content')

<section class="section">

    <x-header>Tambah Point User</x-header>
    {{-- <h2>belum ada data</h2> --}}
    @include('sweetalert::alert')

    <div class="card">
        <div class="card-body">




            <form id="poinform" action="{{ url('admin/topuphistory/point/add') }}" enctype="multipart/form-data"
                method="POST">
                @csrf
                @method('post')
                @if ($errors->any())
                <div style="padding:20px; margin-bottom: 20px" class="aler alert-danger">
                    @foreach ($errors->all() as $err )
                    <li><span>{{ $err }}</span></li>
                    @endforeach
                </div>
                @endif


                <label>Pilih User</label>
                <div class="form-group">
                    <select id="no_hp" name="no_hp" class="form-control select2" style="width:100%!important;">
                        {{-- <option value="" holder></option> --}}
                        @foreach ($users as $item)
                        <option value="{{ $item->no_hp}},{{ $item->id}},{{ $item->name}},{{ $item->poin}}">
                            {{ $item->name }} ( {{ $item->no_hp }}) </option>
                        @endforeach
                    </select>
                </div>

                <label>Point sekarang</label>
                <div class="form-group">
                    <input type="text" readonly="readonly" class="form-control" id="user_point" name="user_point"
                        rows="10">

                </div>


                <label>Pilih aksi</label>
                <div class="form-group">
                    <select id="aksi" name="aksi" class="form-control select2" style="width:100%!important;">
                        {{-- <option value="" holder></option> --}}

                        <option value="penambahan">Tambah</option>
                        <option value="pengurangan">Kurangi</option>

                    </select>
                </div>



                <div class="form-group">
                    <input type="text" class="form-control" id="user" name="user" rows="10">
                </div>
                <x-input id="point" name="point" label="Masukan Jumlah Point" placeholder="0" />


                <button type="button" data-toggle="modal" data-target="#myModal" id="btn_confirm"
                    class="btn btn-primary">Proses Sekarang</button>

            </form>
        </div>


    </div>

</section>
<x-modal id="deleteModal" idForm="deleteForm" title="">
    <x-slot name="footer">
        <x-button color="secondary" title="Batal" data-dismiss="modal" />
        <button type="submit" class="btn btn-info" onclick="formSubmit()">Verifikasi</button>
    </x-slot>
</x-modal>

<script>
    $('#deleteModal').on('show.bs.modal', function () {

$('.modal-title').text('My New Modal Title');

});



    $('#btn_confirm').on('click',  function () {
              $('#deleteModal').modal('show');  
          
              $("#deleteForm").attr('action', url); 
              $("#deleteModal #myModalLabel").text( title );
              $('#deleteModal title').text("Apakah anda ingin memverifikasi top up dengan kode " +data.kode_unik+" ?"); 
               }); 

               
             function formSubmit() { 
                    $("#poinform").submit(); 
            }
            



    document.getElementById("user").style.display = "none";
    data();
    $(function(){
  
    $('.select2').on('change', function() {
        
   data();
    
    });
  });

function data(){
    var data = $(".select2 option:selected").text();
      document.getElementById("user").value = $("#no_hp").val(); 
   
      var str = $("#no_hp").val();
      var n = str.lastIndexOf(',');
      var result = str.substring(n + 1);
      document.getElementById("user_point").value = result ; 
}
  

</script>

@endsection