routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



// Route::get('/', function () {
//     return view('login');
// });

Route::get('clear', function() {
   Artisan::call('config:cache');
   return 'Clear Cache Config Succesfull!';
});


Route::get('/', 'Auth\\LoginController@index')->name('admin.login');
Route::get('admin/tentang/panduan/view', 'TentangController@viewPanduan');
Route::get('admin/tentang/syarat/view', 'TentangController@viewSyarat');
Route::get('admin/tentang/kebijakan/view', 'TentangController@viewKebijakan');
Route::get('admin/tentang/bantuan/view', 'TentangController@viewBantuan');
Auth::routes();






Route::group(['middleware' => 'auth',  'prefix' => 'admin', 'as' => 'admin.'], function () {


    Route::resource('category', 'CategoryController');
    Route::get('/home', 'HomeController@index')->name('admin.home');

    Route::get('user/pengguna', 'UserController@pengguna');
  
  
    Route::get('user/admin', 'UserController@admin');
    Route::get('user/admin/create', 'UserController@adminCreate');
    Route::POST('user/admin/store', 'UserController@adminStore');
    Route::get('user/admin/edit/{id}', 'UserController@adminEdit');
       Route::get('user/admin/edit_list/{id}', 'UserController@adminEditList');
    
    Route::post('user/admin/update/{id}', 'UserController@adminUpdate');
    
       Route::post('user/admin/update/list/{id}', 'UserController@adminUpdateList');
    
    
    Route::post('user/pengguna/status/{id}', 'UserController@statusUSer');
    Route::post('user/pengguna/resetpass/{id}', 'UserController@resetPassUser');
    Route::post('user/pengguna/resetpin/{id}', 'UserController@resetPinUser');

    Route::resource('user', 'UserController');
    Route::resource('tag', 'TagController');
    Route::resource('post', 'PostController');

    Route::resource('roles', 'Admin\RolesController');
    Route::resource('permissions', 'Admin\PermissionsController');

    //baru
    Route::get('slider/api', 'SliderController@sliderAPI');
    Route::resource('slider', 'SliderController');
      Route::resource('slider_berita', 'SliderBeritaController');

    Route::post('topuphistory/masuk/verifikasi/{id}', 'TopUpHistoryController@verifikasiTopupMasuk');
    Route::post('topuphistory/masuk/reject/{id}', 'TopUpHistoryController@rejectTopupMasuk');

    Route::get('topuphistory/masuk', 'TopUpHistoryController@topupMasuk')->name('admin.topuphistory.masuk');
    Route::get('topuphistory/manual', 'TopUpHistoryController@topupManual');
    Route::get('topuphistory/admin_history', 'TopUpHistoryController@adminHistory');

    Route::get('topuphistory/point', 'TopUpHistoryController@tambahPointIndex');
    Route::post('topuphistory/point/add', 'TopUpHistoryController@tambahPoint');
    Route::post('topuphistory/admintopup', 'TopUpHistoryController@tambahkepeng');
    Route::resource('topuphistory', 'TopUpHistoryController');

    Route::get('kirim/history', 'KirimHistoryController@index');

    //pengaturan
    Route::get('pengaturan/fee', 'PengaturanController@fee');
    Route::post('pengaturan/fee/update', 'PengaturanController@updateFee');

    //tentang
    Route::get('tentang/panduan', 'TentangController@panduan');
    Route::get('tentang/syarat', 'TentangController@syarat');
    Route::get('tentang/kebijakan', 'TentangController@kebijakan');
    Route::get('tentang/bantuan', 'TentangController@bantuan');

    Route::get('tentang/', 'TentangController@index');
    Route::post('tentang/panduan/simpan', 'TentangController@storePanduan');
    Route::post('tentang/syarat/simpan', 'TentangController@storeSyarat');
    Route::post('tentang/kebijakan/simpan', 'TentangController@storeKebijakan');
    Route::post('tentang/bantuan/simpan', 'TentangController@storeBantuan');

    //pencairan
    Route::get('pencairan/history', 'PencairanController@history')->name('pencairan.history');
    Route::post('pencairan/verifikasi/{id}', 'PencairanController@verifikasi')->name('pencairan.verifikasi');
    Route::post('pencairan/reject/{id}', 'PencairanController@reject')->name('pencairan.reject');
    Route::resource('pencairan', 'PencairanController');
});


Route::get('autologin', function(){
    Auth::loginUsingId(1);

    return redirect()->to('/');
})->middleware('web');

app/Http/Controllers/SliderBeritaController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PostStoreRequest;
use App\Slider2s;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use RealRashid\SweetAlert\Facades\Alert;

class SliderBeritaController extends Controller
{
    const SLIDER_PATH = 'storage';
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        // $sliders = DB::table('sliders')->select()->get();

        if ($request->ajax()) {

            $slider =  Slider2s::all();
            return datatables()->of($slider)
                ->editColumn('img', function (Slider2s $sliders) {
                    return '<img src="' .  $sliders->getThumbnail() . '" height="100px" width="200px" >';
                })
                ->addColumn('action', 'admin.slider_berita.action')
                ->addIndexColumn()
                ->rawColumns(['img', 'action']) // wajib untuk menmapilkan memproses html misal gambar
                ->make(true);
        }

        return view('admin.slider_berita.index', compact(Slider2s::all()));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        try {
            $sliders = DB::table('slider2s')->select()->get();

            return view('admin.slider_berita.create', compact('sliders'));
        } catch (\Throwable $th) { }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostStoreRequest $request)
    {
        $thumbnail_name = null;
        if ($request->hasFile('thumbnail')) {
              //  $request->file('thumbnail')->store('/storage/upload/'); //store to storage link
            $thumbnail_name = $request->thumbnail->hashName(); // get name only
            // $path = Storage::putFile('/',$request->file('thumbnail'));
            $destinationPath = public_path(SELF::SLIDER_PATH);
            $file = $request->file('thumbnail');
            $file->move($destinationPath, $thumbnail_name);
        };

        DB::table('slider2s')->insert(
            [
                'title'       => $request->title,
                'content'     => $request->content,
                'img'         => $thumbnail_name,
                'created_at'   => \Carbon\Carbon::now()
            ]
        );
        


        Alert::success('Sukses', 'berhasil menambahkan slider');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.javascript:;
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $sliders =  DB::table('slider2s')->where('id', $id)->first();


        return view('admin.slider_berita.edit', compact('sliders'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PostStoreRequest $request, $id)
    {
        
         $slider =  Slider2s::find($id);
         
        $thumbnail_name = null;
        if ($request->hasFile('thumbnail')) {
         //   $request->file('thumbnail')->store('/'); //store to storage link
            $thumbnail_name = $request->thumbnail->hashName(); // get name only
             $path = Storage::putFile('/',
             $request->file('thumbnail'));
        }
        $sliders = DB::table('slider2s')
            ->where('id', $id)
            ->update(
                [
                    'title'   => $request->title,
                    'content' => $request->content,
                    'img'     => $thumbnail_name ?? $slider->img
                ]
            );
             Alert::success('Sukses', 'berhasil memperbarui slider');
              return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $sliders =  DB::table('slider2s')->where('id', $id)->delete();
        return redirect()->route('admin.slider_berita.index');
    }

    public function sliderAPI()
    {
        return response()->json([
            'succes' => true,
            'data' =>  Slider2s::all()
        ]);
    }
}

resources/views/admin/slider_berita/action.blade.php
<a href="{{ route('admin.slider_berita.edit',$id) }}" style="margin-bottom: 10px" class="btn btn-info btn-sm edit"
    role="button" aria-pressed="true"> <i class="fas fa-edit"></i> </a>

<a href="#" id={{ $id }} style="margin-bottom: 10px" class="btn btn-danger btn-sm delete" role="button"
    aria-pressed="true" data-toggle="modal" data-target="#modalDelete"> <i class="fa fa-trash"></i> </a>

resources/views/admin/slider_berita/create.blade.php
@extends('admin.partials.default')
@section('content')
<section class="section">
    <x-header>Tambah Slider Berita</x-header>
    {{-- <h2>belum ada data</h2> --}}

    <div class="card">
        <div class="card-body">
            <form action="{{ route('admin.slider_berita.store') }}" enctype="multipart/form-data" method="POST">
                @csrf
                @if ($errors->any())
                <div style="padding:20px; margin-bottom: 20px" class="aler alert-danger">
                    @foreach ($errors->all() as $err )
                    <li><span>{{ $err }}</span></li>
                    @endforeach
                </div>
                @endif
                <x-input id="title" name="title" label="Title" placeholder="Input Tittle ..." />

                <label>Content</label>
                <div class="form-group">

                    <textarea class="form-control" id="content" name="content" rows="10"
                        style="height: 120px;"></textarea>
                </div>

                <x-input type="file" id="thumbnail" name="thumbnail" label="Thumbnail" />
                <x-button color="success" title="Back" href="{{ route('admin.slider_berita.index')}}" />
                <button type="submit" class="btn btn-primary">Tambah Slider</button>
            </form>
        </div>

    </div>


</section>



@endsection

resources/views/admin/slider_berita/data.blade.php
<script type="text/javascript">
    $(function () {
          $.ajaxSetup({
              headers: {
                  'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
              }
        });
  
        table = $('#tbl-posts').DataTable({
                  processing:true,
                  serverSide:true,
                  pageLength: 5,
                  paging: true,
                  ajax: '{!! route('admin.slider_berita.index') !!}',
                //   url:'admsin/slider/',
                  columns: [
                        { data: 'DT_RowIndex',orderable:false, searchable:false, width:'10px'}, 
                        { data: 'title' },
                        { data: 'img' },
                        { data: 'action', width : '30px' }
                     ]
              }); 
      });



</script>

resources/views/admin/slider_berita/delete.blade.php
<x-modal id="deleteModal" idForm="deleteForm">
    <x-slot name="footer">
        <x-button color="secondary" title="Batal" data-dismiss="modal" />
        <x-button color="danger" title="Hapus data" id="btnDelete" type="submit" />
    </x-slot>
</x-modal>

resources/views/admin/slider_berita/edit.blade.php
@extends('admin.partials.default')
@section('content')
<section class="section">
    <x-header>Edit Slider</x-header>
    {{-- <h2>belum ada data</h2> --}}

    <div class="card">
        <div class="card-body">
            <form role="form" action="{{ route('admin.slider_berita.update', $sliders->id) }}" enctype="multipart/form-data"
                method="POST">
                @csrf
                @method('PUT')
                @if ($errors->any())
                <div style="padding:20px; margin-bottom: 20px" class="aler alert-danger">
                    @foreach ($errors->all() as $err )
                    <li><span>{{ $err }}</span></li>
                    @endforeach
                </div>
                @endif


                <x-input id="title" name="title" label="Title" placeholder="Input Tittle ..."
                    value="{{ $sliders->title }}" />

 <label>Content</label>
                <div class="form-group">

                    <textarea class="form-control" id="content" name="content" rows="10"
                        style="height: 120px;">{{ $sliders->content }}</textarea>
                </div>

           

                <label><b>Thumbnail</b></label><br>

                <img id="img_thum" name="img_thum" style=" padding-bottom:5px"
                    src="{{ asset('/storage/'. $sliders->img) }}" height=" 200px">

                <input type="text" value="default" id="thumb_stat" name="thumb_stat" style="display: none" />

                <div class="form-group">
                    <a id="btnDelThumbnail" href="javascript:void(0)"
                        style=" display: inline-block; margin-bottom: 10px" class="btn btn-danger btn-sm delete"
                        role="button" aria-pressed="true"> <i class="fa fa-trash"></i>
                        Delete thumbnail</a>
                    <br>
                    <input type="file" value="" id="thumbnail" name="thumbnail" onchange="previewImage();" />
                </div>


                <div class="form-group" style="float: right">
                    <x-button color="success" title="Back" href="{{ route('admin.slider_berita.index')}}" />
                    <button type="submit" class="btn btn-primary">Update Slider</button>
                </div>

            </form>
        </div>

    </div>


</section>
<script>
    //Delete img thumnbnail
    $('#btnDelThumbnail').click(function(){
         $("#img_thum").attr("src","https://via.placeholder.com/150x200.png?text=No+Cover");
         document.getElementById("btnDelThumbnail").style.display = "none";
         $("#thumb_stat").val("hapus");

    });

    //check kondisi jika image null/ tidak ada cover
    let thumbnail = {!! json_encode('/storage/upload/'. $sliders->img) !!} ;
    if(thumbnail=='https://via.placeholder.com/150x200.png?text=No+Cover'){
        document.getElementById("btnDelThumbnail").style.display = "none";
    }


    //Reload ketika image di pilih dari direktori
    function previewImage() {
        document.getElementById("img_thum").style.display = "block";
        var oFReader = new FileReader();
        oFReader.readAsDataURL(document.getElementById("thumbnail").files[0]);
    
        oFReader.onload = function(oFREvent) {
            document.getElementById("img_thum").src = oFREvent.target.result;
            document.getElementById("btnDelThumbnail").style.display = "inline-block";

        };
       
    };



</script>


@endsection

resources/views/admin/slider_berita/index.blade.php
@extends('admin.partials.default')
@section('content')
<section class="section">

    <x-header>Slider Berita</x-header>
    <x-button id="btnCreate" style="margin-bottom: 10px" title="Tambah Slider"
        href="{{ route('admin.slider_berita.create') }}">
    </x-button>

    @table([ 'th' => ['No', 'Title','Image','Action'],
    'id' => 'tbl-posts'])

</section>
<form id="deleteForm" method="POST" role="form">
    @csrf
    @method('delete')
    <x-modal id="deleteModal" idForm="deleteForm" title="Apakah anda yakin ingin menghapus post ?">
        <x-slot name="footer">
            <x-button color="secondary" title="Batal" data-dismiss="modal" />
            <button type="submit" class="btn btn-danger" onclick="formSubmit()">Delete Data</button>
        </x-slot>
    </x-modal>
</form>

@include('admin.slider_berita.data');
<script>
    $('#tbl-posts tbody').on('click', '.delete', function () {
              $('#deleteModal').modal('show');  
              id = $(this).attr('id'); 
              var url = 'slider_berita/' + id;
              $(" #deleteForm").attr('action', url); let data=table.row( $(this).parents('tr') ).data();
              $('#deleteModal .modal-title').text("Yakin ingin menghapus Post, " +data.title+" ?"); }); 
             
             function formSubmit() { 
                    $("#deleteForm").submit(); 
                } 
</script>
@endsection