routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



// Route::get('/', function () {
//     return view('login');
// });

Route::get('clear', function() {
   Artisan::call('config:cache');
   return 'Clear Cache Config Succesfull!';
});


Route::get('/', 'Auth\\LoginController@index')->name('admin.login');
Route::get('admin/tentang/panduan/view', 'TentangController@viewPanduan');
Route::get('admin/tentang/syarat/view', 'TentangController@viewSyarat');
Route::get('admin/tentang/kebijakan/view', 'TentangController@viewKebijakan');
Route::get('admin/tentang/bantuan/view', 'TentangController@viewBantuan');
Auth::routes();






Route::group(['middleware' => 'auth',  'prefix' => 'admin', 'as' => 'admin.'], function () {


    Route::resource('category', 'CategoryController');
    Route::get('/home', 'HomeController@index')->name('admin.home');

    Route::get('user/pengguna', 'UserController@pengguna');
  
  
    Route::get('user/admin', 'UserController@admin');
    Route::get('user/admin/create', 'UserController@adminCreate');
    Route::POST('user/admin/store', 'UserController@adminStore');
    Route::get('user/admin/edit/{id}', 'UserController@adminEdit');
       Route::get('user/admin/edit_list/{id}', 'UserController@adminEditList');
    
    Route::post('user/admin/update/{id}', 'UserController@adminUpdate');
    
       Route::post('user/admin/update/list/{id}', 'UserController@adminUpdateList');
    
    
    Route::post('user/pengguna/status/{id}', 'UserController@statusUSer');
    Route::post('user/pengguna/resetpass/{id}', 'UserController@resetPassUser');
    Route::post('user/pengguna/resetpin/{id}', 'UserController@resetPinUser');

    Route::resource('user', 'UserController');
    Route::resource('tag', 'TagController');
    Route::resource('post', 'PostController');

    Route::resource('roles', 'Admin\RolesController');
    Route::resource('permissions', 'Admin\PermissionsController');

    //baru
    Route::get('slider/api', 'SliderController@sliderAPI');
    Route::resource('slider', 'SliderController');
      Route::resource('slider_berita', 'SliderBeritaController');

    Route::post('topuphistory/masuk/verifikasi/{id}', 'TopUpHistoryController@verifikasiTopupMasuk');
    Route::post('topuphistory/masuk/reject/{id}', 'TopUpHistoryController@rejectTopupMasuk');

    Route::get('topuphistory/masuk', 'TopUpHistoryController@topupMasuk')->name('admin.topuphistory.masuk');
    Route::get('topuphistory/manual', 'TopUpHistoryController@topupManual');
    Route::get('topuphistory/admin_history', 'TopUpHistoryController@adminHistory');

    Route::get('topuphistory/point', 'TopUpHistoryController@tambahPointIndex');
    Route::post('topuphistory/point/add', 'TopUpHistoryController@tambahPoint');
    Route::post('topuphistory/admintopup', 'TopUpHistoryController@tambahkepeng');
    Route::resource('topuphistory', 'TopUpHistoryController');

    Route::get('kirim/history', 'KirimHistoryController@index');

    //pengaturan
    Route::get('pengaturan/fee', 'PengaturanController@fee');
    Route::post('pengaturan/fee/update', 'PengaturanController@updateFee');

    //tentang
    Route::get('tentang/panduan', 'TentangController@panduan');
    Route::get('tentang/syarat', 'TentangController@syarat');
    Route::get('tentang/kebijakan', 'TentangController@kebijakan');
    Route::get('tentang/bantuan', 'TentangController@bantuan');

    Route::get('tentang/', 'TentangController@index');
    Route::post('tentang/panduan/simpan', 'TentangController@storePanduan');
    Route::post('tentang/syarat/simpan', 'TentangController@storeSyarat');
    Route::post('tentang/kebijakan/simpan', 'TentangController@storeKebijakan');
    Route::post('tentang/bantuan/simpan', 'TentangController@storeBantuan');

    //pencairan
    Route::get('pencairan/history', 'PencairanController@history')->name('pencairan.history');
    Route::post('pencairan/verifikasi/{id}', 'PencairanController@verifikasi')->name('pencairan.verifikasi');
    Route::post('pencairan/reject/{id}', 'PencairanController@reject')->name('pencairan.reject');
    Route::resource('pencairan', 'PencairanController');
});


Route::get('autologin', function(){
    Auth::loginUsingId(1);

    return redirect()->to('/');
})->middleware('web');

resources/views/admin/partials/default.blade.php
<!DOCTYPE html>
<html lang="en">

@include('admin.partials.head')


<body>
  <div id="app">
    <div class="main-wrapper">
      <div class="navbar-bg"></div>

      @include('admin.partials.header')
      @include('admin.partials.sidebar')

      <!-- Main Content -->
      <div class="main-content">
        <div class="row">
          <div class="col-12 ">
            @include('sweetalert::alert')
            @yield('content')
          </div>

        </div>
      </div>
      @include('admin.partials.footer')
    </div>
  </div>
  @include('admin.partials.scripts')

</body>

<script>

</script>

</html>

resources/views/admin/partials/footer.blade.php
<footer class="main-footer">
  {{-- <div class="footer-left">
      Copyright &copy; 2018 <div class="bullet"></div> Design By <a href="https://nauval.in/">Muhamad Nauval Azhar</a>
    </div> --}}
  <div class="footer-right">
    2.3.0
  </div>
</footer>

resources/views/admin/partials/head.blade.php
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Kepeng</title>

    <!-- General CSS Files -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet">
    {{-- <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css"> --}}
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.6/css/buttons.dataTables.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>


    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
        integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/izitoast/1.4.0/css/iziToast.min.css">

    <!-- Template CSS -->
    <link rel="stylesheet" href="{{ asset('assets/css/style.css')}}">
    <link rel="stylesheet" href="{{ asset('assets/css/components.css')}}">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />

    <script src="//cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.6/numeral.min.js"></script>

    <script src="//cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>




</head>

resources/views/admin/partials/header.blade.php
<nav class="navbar navbar-expand-lg main-navbar">
  <form class="form-inline mr-auto">
    <ul class="navbar-nav mr-3">
      <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
      <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li>
    </ul>
    <div class="search-element">
      <input class="form-control" type="search" placeholder="Search" aria-label="Search" data-width="250">
      <button class="btn" type="submit"><i class="fas fa-search"></i></button>
      <div class="search-backdrop"></div>

    </div>
  </form>
  
    <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
        <img alt="image" src="{{ asset('assets/img/avatar/avatar-1.png') }}" class="rounded-circle mr-1">
        <div class="d-sm-none d-lg-inline-block">Hi, {{ Auth::user()->name }}</div>
      </a>
      <div class="dropdown-menu dropdown-menu-right">
        {{-- <div class="dropdown-title">Logged in 5 min ago</div> --}}
        {{-- <a href="features-profile.html" class="dropdown-item has-icon">
          <i class="far fa-user"></i> Profile
        </a> --}}
        {{-- <a href="features-activities.html" class="dropdown-item has-icon">
          <i class="fas fa-bolt"></i> Activities
        </a> --}}
        <a href="{{ url('/admin/user/admin/edit',  Auth::user()->id) }}" class="dropdown-item has-icon">
          <i class="fas fa-cog"></i> Settings
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item has-icon text-danger"
          onclick="event.preventDefault();  document.getElementById('logout-form').submit();">
          <i class=" fas fa-sign-out-alt"></i> {{ __('Logout') }}
        </a>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
          @csrf
        </form>
      </div>
    </li>
  </ul>
</nav>

resources/views/admin/partials/modal.blade.php
<div class="modal {{ $animation ?? 'fade' }} {{ $class ?? '' }}" id="{{ $id }}">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            @isset($title)
            <div class="modal-header">
                <h5 class="modal-title">{{ $title }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @endisset

            <div class="modal-body">
                {{ $slot }}
            </div>

            @isset($footer)
            <div class="modal-footer">
                {{ $footer }}
            </div>
            @endisset
        </div>
    </div>
</div>

resources/views/admin/partials/scripts.blade.php
<!-- General JS Scripts -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
  integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
  integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
<script src="{{ asset('assets/js/stisla.js') }}"></script>

<!-- Js libraries -->
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/izitoast/1.4.0/js/iziToast.min.js"></script>


<!-- Template JS File -->
<script src="{{ asset('assets/js/scripts.js') }}"></script>
<script src="{{ asset('assets/js/custom.js') }}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>


{{-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script> --}}
{{-- <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script> --}}
<script src="https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.flash.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.print.min.js"></script>

resources/views/admin/partials/sidebar.blade.php
<div class="main-sidebar">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand">
            <a href="#">Kepeng Admin</a>
        </div>
        <div class="sidebar-brand sidebar-brand-sm">
            <a href="index.html">KEPENG</a>
        </div>
        <ul class="sidebar-menu">
            <li class="menu-header">Dashboard</li>
            <li class=" nav-item dropdown">
            <li class="">
                <a href="{{ url('admin/home') }}" class="nav-link"><i class=" fas
            fa-home"></i><span>Dashboard</span></a>
            </li>
            </li>
            <li class="menu-header">Menu</li>
            <li class="">


                @if(Auth::user()->hak_akses_id=='1')
            <li class="nav-item dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="fa fa-history"></i>
                    <span>Top Up</span></a>


                <ul class="dropdown-menu">
                    <li><a class="nav-link active" href="{{ url('admin/topuphistory/masuk') }}"><i class=" far
                            fa-sticky-note"></i><span>Topup Masuk</span></a></li>
                    <li> <a class="nav-link active" href="{{ url('admin/topuphistory/manual') }}"><i class=" far
                                fa-sticky-note"></i><span>Topup Kepeng</span></a></li>
                    <li> <a class="nav-link active" href="{{ url('admin/topuphistory/point') }}"><i class=" far
                                    fa-sticky-note"></i><span>Topup Point</span></a></li>

                </ul>
            </li>


            <li class="nav-item">
                <a href="{{ route('admin.pencairan.index') }}" class="nav-link"><i class="fa fa-history"></i>
                    <span>Pencairan</span></a>
            </li>
            @endif


            </li>




            <li class="nav-item dropdown ">
                <a href="#" class="nav-link has-dropdown"><i class="fa fa-history"></i> <span>History</span></a>
                <ul class="dropdown-menu">
                    <li><a class=" nav-link" href="{{ route('admin.topuphistory.index') }}">
                            Top Up User</a>
                    </li>
                    <li><a class=" nav-link" href="{{ url('admin/kirim/history') }}">
                            Transfer User</a>
                    </li>
                    <li><a class=" nav-link" href="{{ url('admin/topuphistory/admin_history') }}">
                            Admin History</a>
                    </li>
                    <li><a class=" nav-link" href="{{ url('admin/pencairan/history') }}">
                        Pencairan History</a>
                </li>

                </ul>
            </li>


            <li class="nav-item dropdown ">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-user-friends"></i>
                    <span>User</span></a>


                <ul class="dropdown-menu">
                    <li><a class=" nav-link" href="{{ url('admin/user/pengguna') }}">
                            Pengguna</a>
                    </li>

                    @if(Auth::user()->hak_akses_id=='1')
                    <li><a class=" nav-link" href="{{ url('admin/user/admin') }}">
                            Admin</a>
                    </li>
                    @endif


                </ul>
            </li>

            <li class="nav-item dropdown ">
                @if(Auth::user()->hak_akses_id=='1')
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-cog"></i> <span>Pengaturan</span></a>
                @endif
                <ul class="dropdown-menu">
                    <li><a class=" nav-link" href="{{ url('admin/pengaturan/fee') }}">Transaction Fee</a>
                    </li>
                    <li><a class=" nav-link" href="{{ url('admin/slider') }}">Slider Promo
                      <li><a class=" nav-link" href="{{ url('admin/slider_berita') }}">Slider Berita
                    <li><a class=" nav-link" href="{{ url('admin/tentang/') }}">Tentang App Mobile</a>
                    </li>


                </ul>
            </li>


        </ul>
    </aside>
</div>

resources/views/admin/partials/sidebarbackup.blade.php
<div class="main-sidebar">
  <aside id="sidebar-wrapper">
    <div class="sidebar-brand">
      <a href="#">Blog APP</a>
    </div>
    <div class="sidebar-brand sidebar-brand-sm">
      <a href="index.html">St</a>
    </div>
    <ul class="sidebar-menu">
      <li class="menu-header">Dashboard</li>
      <li class=" nav-item dropdown">
      <li class="{{set_active('admin.home')}}">
        <a href="{{ url('admin/home') }}" class="nav-link"><i class=" fas
          fa-home"></i><span>Dashboard</span></a>
      </li>
      </li>
      <li class="menu-header">Menu</li>
      <li class="{{set_active('admin.post.index')}}">

        <a class="nav-link active" href="{{ route('admin.post.index') }}"><i
            class="far fa-sticky-note"></i><span>Posts</span>

        </a>

      </li>
      <li class="{{set_active('admin.category.index')}}"><a class="nav-link"
          href="{{ route('admin.category.index') }}"><i class="fas fa-th-list"></i><span>Category</span></a>
      </li>

      <li class="{{ set_active('admin.tag.index') }}"><a class="nav-link" href="{{ route('admin.tag.index') }}"><i
            class="fas fa-tags"></i><span>Tag</span></a>
      </li>

      <li class="nav-item dropdown {{set_active('admin.user.index')}}">
        <a href="#" class="nav-link has-dropdown"><i class="fas fa-user-friends"></i> <span>Users Management</span></a>
        <ul class="dropdown-menu">
          <li><a class=" nav-link" href="{{ route('admin.user.index') }}">
              Permissions</a>
          </li>
          <li><a class=" nav-link" href="{{ route('admin.roles.index') }}">
              Roles</a>
          </li>
          <li><a class=" nav-link" href="{{ route('admin.user.index') }}">
              Users</a>
          </li>
        </ul>
      </li>
      <li class="nav-item dropdown">
        <a href="#" class="nav-link has-dropdown"><i class="fas fa-palette"></i><span>Customize</span></a>
        <ul class="dropdown-menu">
          <li><a class=" nav-link" href="{{ route('admin.user.index') }}">Header</a>
          <li><a class=" nav-link" href="{{ route('admin.user.index') }}">Menu</a>
          <li><a class=" nav-link" href="{{ route('admin.user.index') }}">Sidebar</a>
          <li><a class=" nav-link" href="{{ route('admin.user.index') }}">Slider</a>
          <li><a class=" nav-link" href="{{ route('admin.user.index') }}">Footer</a>
          </li>
        </ul>
      </li>
      <li><a class="nav-link" href="{{ route('admin.category.index') }}"><i
            class="fas fa-cog"></i><span>Settings</span></a>
      </li>
    </ul>
  </aside>
</div>